/* Generated by re2c 1.3 on Fri Feb 11 01:42:25 2022 */
#line 1 "lexer.l"
//--------------------------------------------------------- ./scanner.l

#include <php.h>
#include "lexer.h"
#include "ext/pcre/php_pcre.h"
#include "php_aop.h"

int scan(scanner_state *s, scanner_token *t) {

    // char *cursor = s->start;
    int r=SCANNER_RETCODE_IMPOSSIBLE;
    char *q=s->start;//keep initial start

#define YYCTYPE char
#define YYCURSOR (s->start)
#define YYMARKER (s->marker)

    while(SCANNER_RETCODE_IMPOSSIBLE == r) {


#line 25 "<stdout>"
        {
            YYCTYPE yych;
            yych = *YYCURSOR;
            switch (yych) {
                case 0x00:      goto yy2;
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case '"':
                case '#':
                case '%':
                case '&':
                case '\'':
                case ')':
                case '+':
                case ',':
                case '.':
                case '/':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '}':
                case '~':       goto yy4;
                case '\t':
                case ' ':
                case '$':       goto yy6;
                case '!':       goto yy9;
                case '(':       goto yy10;
                case '-':       goto yy14;
                case ':':       goto yy15;
                case 'P':
                case 'p':       goto yy16;
                case 'R':
                case 'r':       goto yy17;
                case 'S':
                case 's':       goto yy18;
                case 'W':
                case 'w':       goto yy19;
                case '|':       goto yy20;
                default:        goto yy11;
            }
            yy2:
            ++YYCURSOR;
#line 101 "lexer.l"
            { r = SCANNER_RETCODE_EOF; break; }
#line 106 "<stdout>"
            yy4:
            ++YYCURSOR;
            yy5:
#line 103 "lexer.l"
            { r = SCANNER_RETCODE_ERR; break; }
#line 112 "<stdout>"
            yy6:
            yych = *++YYCURSOR;
            switch (yych) {
                case '\t':
                case ' ':
                case '$':       goto yy6;
                default:        goto yy8;
            }
            yy8:
#line 97 "lexer.l"
            {
                t->TOKEN = TOKEN_SPACE;
                return 0;
            }
#line 127 "<stdout>"
            yy9:
            yych = *(YYMARKER = ++YYCURSOR);
            switch (yych) {
                case 'P':
                case 'p':       goto yy22;
                case 'S':
                case 's':       goto yy24;
                default:        goto yy5;
            }
            yy10:
            yych = *++YYCURSOR;
            if (yych == ')') {
                goto yy25;
            } else {
                goto yy5;
            }
            yy11:
            yych = *++YYCURSOR;
            yy12:
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy13;
                default:        goto yy11;
            }
            yy13:
#line 92 "lexer.l"
            {
                t->str_val = estrndup(q,YYCURSOR - q);
                t->TOKEN = TOKEN_TEXT;
                return 0;
            }
#line 218 "<stdout>"
            yy14:
            yych = *++YYCURSOR;
            if (yych == '>') {
                goto yy27;
            } else {
                goto yy5;
            }
            yy15:
            yych = *++YYCURSOR;
            if (yych == ':') {
                goto yy29;
            } else {
                goto yy5;
            }
            yy16:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'R':
                case 'r':       goto yy31;
                case 'U':
                case 'u':       goto yy32;
                default:        goto yy12;
            }
            yy17:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy33;
                default:        goto yy12;
            }
            yy18:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy34;
                default:        goto yy12;
            }
            yy19:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'R':
                case 'r':       goto yy35;
                default:        goto yy12;
            }
            yy20:
            ++YYCURSOR;
#line 68 "lexer.l"
            {
                t->TOKEN = TOKEN_OR;
                return 0;
            }
#line 268 "<stdout>"
            yy22:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'R':
                case 'r':       goto yy36;
                case 'U':
                case 'u':       goto yy37;
                default:        goto yy23;
            }
            yy23:
            YYCURSOR = YYMARKER;
            goto yy5;
            yy24:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy38;
                default:        goto yy23;
            }
            yy25:
            ++YYCURSOR;
#line 26 "lexer.l"
            {
                t->TOKEN = TOKEN_FUNCTION;
                return 0;
            }
#line 295 "<stdout>"
            yy27:
            ++YYCURSOR;
#line 30 "lexer.l"
            {
                t->TOKEN = TOKEN_CLASS;
                return 0;
            }
#line 303 "<stdout>"
            yy29:
            ++YYCURSOR;
#line 34 "lexer.l"
            {
                t->TOKEN = TOKEN_CLASS;
                return 0;
            }
#line 311 "<stdout>"
            yy31:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy39;
                case 'O':
                case 'o':       goto yy40;
                default:        goto yy12;
            }
            yy32:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'B':
                case 'b':       goto yy41;
                default:        goto yy12;
            }
            yy33:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'A':
                case 'a':       goto yy42;
                default:        goto yy12;
            }
            yy34:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'A':
                case 'a':       goto yy43;
                default:        goto yy12;
            }
            yy35:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy44;
                default:        goto yy12;
            }
            yy36:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy45;
                case 'O':
                case 'o':       goto yy46;
                default:        goto yy23;
            }
            yy37:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'B':
                case 'b':       goto yy47;
                default:        goto yy23;
            }
            yy38:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'A':
                case 'a':       goto yy48;
                default:        goto yy23;
            }
            yy39:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'V':
                case 'v':       goto yy49;
                default:        goto yy12;
            }
            yy40:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy50;
                default:        goto yy12;
            }
            yy41:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'L':
                case 'l':       goto yy51;
                default:        goto yy12;
            }
            yy42:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'D':
                case 'd':       goto yy52;
                default:        goto yy12;
            }
            yy43:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy54;
                default:        goto yy12;
            }
            yy44:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy55;
                default:        goto yy12;
            }
            yy45:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'V':
                case 'v':       goto yy56;
                default:        goto yy23;
            }
            yy46:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy57;
                default:        goto yy23;
            }
            yy47:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'L':
                case 'l':       goto yy58;
                default:        goto yy23;
            }
            yy48:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy59;
                default:        goto yy23;
            }
            yy49:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'A':
                case 'a':       goto yy60;
                default:        goto yy12;
            }
            yy50:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy61;
                default:        goto yy12;
            }
            yy51:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy62;
                default:        goto yy12;
            }
            yy52:
            yych = *++YYCURSOR;
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy53;
                default:        goto yy11;
            }
            yy53:
#line 38 "lexer.l"
            {
                t->TOKEN = TOKEN_PROPERTY;
                t->int_val = AOP_KIND_READ;
                return 0;
            }
#line 537 "<stdout>"
            yy54:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy63;
                default:        goto yy12;
            }
            yy55:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy64;
                default:        goto yy12;
            }
            yy56:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'A':
                case 'a':       goto yy66;
                default:        goto yy23;
            }
            yy57:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy67;
                default:        goto yy23;
            }
            yy58:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy68;
                default:        goto yy23;
            }
            yy59:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'I':
                case 'i':       goto yy69;
                default:        goto yy23;
            }
            yy60:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy70;
                default:        goto yy12;
            }
            yy61:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'C':
                case 'c':       goto yy71;
                default:        goto yy12;
            }
            yy62:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'C':
                case 'c':       goto yy72;
                default:        goto yy12;
            }
            yy63:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'C':
                case 'c':       goto yy74;
                default:        goto yy12;
            }
            yy64:
            yych = *++YYCURSOR;
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy65;
                default:        goto yy11;
            }
            yy65:
#line 43 "lexer.l"
            {
                t->TOKEN = TOKEN_PROPERTY;
                t->int_val = AOP_KIND_WRITE;
                return 0;
            }
#line 682 "<stdout>"
            yy66:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy76;
                default:        goto yy23;
            }
            yy67:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'C':
                case 'c':       goto yy77;
                default:        goto yy23;
            }
            yy68:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'C':
                case 'c':       goto yy78;
                default:        goto yy23;
            }
            yy69:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'C':
                case 'c':       goto yy80;
                default:        goto yy23;
            }
            yy70:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy82;
                default:        goto yy12;
            }
            yy71:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy84;
                default:        goto yy12;
            }
            yy72:
            yych = *++YYCURSOR;
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy73;
                default:        goto yy11;
            }
            yy73:
#line 48 "lexer.l"
            {
                t->TOKEN = TOKEN_SCOPE;
                t->int_val = ZEND_ACC_PUBLIC;
                return 0;
            }
#line 799 "<stdout>"
            yy74:
            yych = *++YYCURSOR;
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy75;
                default:        goto yy11;
            }
            yy75:
#line 63 "lexer.l"
            {
                t->TOKEN = TOKEN_STATIC;
                t->int_val = 1;
                return 0;
            }
#line 874 "<stdout>"
            yy76:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy85;
                default:        goto yy23;
            }
            yy77:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'T':
                case 't':       goto yy87;
                default:        goto yy23;
            }
            yy78:
            ++YYCURSOR;
#line 72 "lexer.l"
            {
                t->TOKEN = TOKEN_SCOPE;
                t->int_val  = ZEND_ACC_PROTECTED | ZEND_ACC_PRIVATE;
                return 0;
            }
#line 897 "<stdout>"
            yy80:
            ++YYCURSOR;
#line 87 "lexer.l"
            {
                t->TOKEN = TOKEN_STATIC;
                t->int_val = 0;
                return 0;
            }
#line 906 "<stdout>"
            yy82:
            yych = *++YYCURSOR;
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy83;
                default:        goto yy11;
            }
            yy83:
#line 58 "lexer.l"
            {
                t->TOKEN = TOKEN_SCOPE;
                t->int_val = ZEND_ACC_PRIVATE;
                return 0;
            }
#line 981 "<stdout>"
            yy84:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy88;
                default:        goto yy12;
            }
            yy85:
            ++YYCURSOR;
#line 82 "lexer.l"
            {
                t->TOKEN = TOKEN_SCOPE;
                t->int_val  = ZEND_ACC_PUBLIC | ZEND_ACC_PROTECTED;
                return 0;
            }
#line 997 "<stdout>"
            yy87:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'E':
                case 'e':       goto yy89;
                default:        goto yy23;
            }
            yy88:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'D':
                case 'd':       goto yy90;
                default:        goto yy12;
            }
            yy89:
            yych = *++YYCURSOR;
            switch (yych) {
                case 'D':
                case 'd':       goto yy92;
                default:        goto yy23;
            }
            yy90:
            yych = *++YYCURSOR;
            switch (yych) {
                case 0x00:
                case 0x01:
                case 0x02:
                case 0x03:
                case 0x04:
                case 0x05:
                case 0x06:
                case 0x07:
                case 0x08:
                case '\t':
                case '\n':
                case '\v':
                case '\f':
                case '\r':
                case 0x0E:
                case 0x0F:
                case 0x10:
                case 0x11:
                case 0x12:
                case 0x13:
                case 0x14:
                case 0x15:
                case 0x16:
                case 0x17:
                case 0x18:
                case 0x19:
                case 0x1A:
                case 0x1B:
                case 0x1C:
                case 0x1D:
                case 0x1E:
                case 0x1F:
                case ' ':
                case '!':
                case '"':
                case '#':
                case '$':
                case '%':
                case '&':
                case '\'':
                case '(':
                case ')':
                case '+':
                case ',':
                case '-':
                case '.':
                case '/':
                case ':':
                case ';':
                case '<':
                case '=':
                case '>':
                case '?':
                case '@':
                case '[':
                case ']':
                case '^':
                case '`':
                case '{':
                case '|':
                case '}':
                case '~':       goto yy91;
                default:        goto yy11;
            }
            yy91:
#line 53 "lexer.l"
            {
                t->TOKEN = TOKEN_SCOPE;
                t->int_val = ZEND_ACC_PROTECTED;
                return 0;
            }
#line 1093 "<stdout>"
            yy92:
            ++YYCURSOR;
#line 77 "lexer.l"
            {
                t->TOKEN = TOKEN_SCOPE;
                t->int_val  = ZEND_ACC_PUBLIC | ZEND_ACC_PRIVATE;
                return 0;
            }
#line 1102 "<stdout>"
        }
#line 104 "lexer.l"

    }
    return r;
}